#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="uptimekuma"
prepare_service 20-uptimekuma

check_container_initialized
check_service_initialized init

case "${LOG_TYPE,,}" in
    both )
        out=/dev/stdout
        pipe="sudo -u uptimekuma tee -a ${LOG_PATH$/}/${LOG_FILE}"
    ;;
    console )
        out=/dev/stdout
        pipe="cat"
    ;;
    file )
        out="${LOG_PATH%/}/${LOG_FILE}"
        pipe="silent tee /dev/null"
    ;;
esac

export NODE_ENVIRONMENT=production
export PORT=${LISTEN_PORT}
liftoff

print_start "Starting Uptime Kuma ${UPTIMEKUMA_VERSION}"
cd /app
s6-setuidgid uptimekuma \
                        exec node \
                                    server/server.js 2>&1 >> "${out}" 2>&1 | ${pipe}